export default {
  INDEX: '/',
  USER: '/users',
  LOGIN: '/login',
  PROFILE: '/me',
  LOGOUT: '/me/logout',
  API: '/api',
  REGISTER: '/register',
  WORKSPACE: '/workspace',
  LOCATION: '/location',
  ADD: '/add',
  BOOKINGS: '/bookings',
  CREATE: '/create',
  CANCEL: '/cancel',
  MYBOOKINGS: '/mybookings',
  BOOKEDSLOTS: '/bookedslots',
  ROOM: '/room',
  UPDATE: '/me/update',
};
